---
title: "Week 4 Homework Example"
author: "Nicholas Good"
output:
  html_document: default
  pdf_document: default
---

```{r global_options, include = FALSE}
  knitr::opts_chunk$set(fig.path = 'figures/',
                        warning = FALSE,
                        message = FALSE,
                        fig.width = 6, fig.height = 10,
                        cache = FALSE)
```

---

# Libraries

```{r libraries}
library(tidyverse)
library(knitr)
```

---

# Read homicide data

* use `"../"` because markdown is in the `output` folder

* the `col_types = cols()` prevents warning message

```{r}
raw_data <- read_csv("../data/homicide-data.csv",
                     col_types = cols())
```

---

# Manipulate raw data

* add a column with the city and state combined
* print the first line

```{r}
homicide_data <- raw_data %>%
                 mutate(city_name = paste0(city, ", ", state))
```

```{r, echo = FALSE}
kable(head(homicide_data %>%
      select(city, state, city_name), 1))
```

---

# Unsolved homicides

* fix messy data
* summarise
* organize

```{r}
unsolved <- homicide_data %>%
            filter(!is.na(city)) %>%
            mutate(disposition = sub("<.*", "", disposition),
                   disposition = tolower(gsub(" |/",  "_", disposition)),
                   disposition = factor(disposition)) %>%
            group_by(city, disposition) %>%
            summarise(num = n()) %>%
            spread(disposition, num) %>%
            mutate(n_total = closed_by_arrest +
                             closed_without_arrest +
                             open_no_arrest,
                   n_unsolved = open_no_arrest + closed_without_arrest) %>%
            select(city, n_total, n_unsolved)
```

* check

```{r, echo = FALSE}
kable(head(unsolved , 5))
```

---





